### PR TITLE
fix: add informative titles to each non-dynamic route in 'website'

### PR DESCRIPTION
**Pull request by oneminch**

### CODE REVIEW

**Comment by uncenter** [comment]
Two things. First, you can use a template for the titles instead of repeating `- umami` every time: https://nextjs.org/docs/app/api-reference/functions/generate-metadata#template. Second, this is much much better but there is still no distinction between individual pages on the docs since everything is just `Docs - umami`. It would be nice to have page titles like `Installation - umami` and `Authentication - umami` or something.

**Comment by uncenter** [comment]
For the second suggestion you could just do https://nextjs.org/docs/app/api-reference/functions/generate-metadata#generatemetadata-function?

**Comment by oneminch** [comment]
I'll read on that and figure that out. I noticed dynamic routes that use MDX including blog posts need metadata.

**Comment by oneminch** [comment]
> For the second suggestion you could just do https://nextjs.org/docs/app/api-reference/functions/generate-metadata#generatemetadata-function?

I have made it so that it uses a template and each dynamic route has a title, including v1 of the docs. V1 doc pages have a template of `title - umami (v1)`. Sorry I packed a lot of changes in a single commit.

Basically what I did was to add the title template to the main layout file and export a minimal title from each page. For the docs and blog posts, I exported a single `meta` object from each MDX file, and generate its title dynamically from the `page`.

**Comment by uncenter** [comment]
Nice job! Looks great.

**Comment by oneminch** [comment]
That's the only way I can think of that makes sense to me. I think of it like frontmatter. 

My initial approach was to parse the 'menu.json' files and use the slug/id to get the title. But, if you want to add other metadata that's good for SEO such as 'description', the current approach makes sense to me.

**Comment by uncenter** [comment]
Gotcha, thanks for explaining. Makes sense to me!

**Review by mikecao — APPROVED** [review]
👍

**Comment by mikecao** [comment]
@oneminch The conflicting files above have moved. I think if you just do a pull then we can merge.

**Pull request merged**
