### PR TITLE
Improve docs sidebar

### LINKED ISSUE #131: Docs navigation issues
In the process of editing and reviewing the documentation I realized a few issues that were negatively impacting my experience enough to make an issue about.

## Scrolling issues
When scrolling down a long page, the side menu doesn't begin to scroll until near the bottom because it doesn't have it's own independent scrolling. If I click on an item in the side menu towards the bottom and the new section loads, the scroll position resets - meaning you can't easily switch between sections and keep track of your place. A good example that we should try to emulate is https://nextjs.org/docs.

## Image quality

It seems like the images are super blurry to me! Not super important but just a small QOL thing. It would be nice to retake them and make them appear more consistent as well, and we could add some sort of optimization/processing during build if necessary.

### PR DESCRIPTION
**Pull request by uncenter**
This PR adds a separate scrollbar for the sidebar and also adds a dropdown to select a docs version (v1 or v2). Closes #131.

### CODE REVIEW

**Comment by uncenter** [comment]
@mikecao I'm trying to get the `Dropdown` component from `react-basics` to work but it won't expand with any items even though I copied the example right from https://umami-software.github.io/react-basics/?path=/docs/input-dropdown--docs.

**Comment by uncenter** [comment]
There's this annoying layout shift on load since the calculations for the styling of the sidebar involve the height of the page, which doesn't happen for a bit until the content loads in. Is there a reason it doesn't load in right away?

**Comment by uncenter** [comment]
Fixed!

**Comment by uncenter** [comment]
Seems to be no interest in outside contributions. If you want to fix this annoying issue, I'll reopen this.

**Comment by mikecao** [comment]
@uncenter Just implemented your changes on the website. Thanks!

**Comment by uncenter** [comment]
And I like the toggle between Open-source and Cloud, what do you think about a v1/v2 dropdown for the open-source side?

**Comment by uncenter** [comment]
Hmm. It looks like it is working *kinda* on desktop. Also not sure what changes you made to how the pages are rendered, but if you look at the latest deployment of this PR you can click any link and only the text changes - not the whole page. That means that the sidebar stays in the same position.

**Current live site**:

https://github.com/umami-software/website/assets/47499684/a3319125-f974-4a26-b6b4-d8728ec21bdb

**Latest deployment of this PR:**

https://github.com/umami-software/website/assets/47499684/902ff51b-cd09-49c9-8179-dde375b0d830

**Comment by uncenter** [comment]
Another thing I'd like to point out is both my implementation and yours don't work great on mobile:

**Comment by uncenter** [comment]
> Hmm. It looks like it is working _kinda_ on desktop. Also not sure what changes you made to how the pages are rendered, but if you look at the latest deployment of this PR you can click any link and only the text changes - not the whole page. That means that the sidebar stays in the same position. Now it looks like the whole page reloads maybe?
> 
> **Current live site**:
> 
>  Screenshot.2023-12-14.at.06.05.05.Arc.mp4 
> **Latest deployment of this PR:**
> 
>  Screenshot.2023-12-14.at.06.05.46.Arc.mp4

Looks like this has been fixed! Thanks. The mobile issue is still present though.

**Comment by mikecao** [comment]
@uncenter New expandable docs menu for mobile
image

**Pull request closed without merging**
