### PR TITLE
docs: fix spelling, capitalization, and grammar issues

### PR DESCRIPTION
**Pull request by uncenter**
Fixes some spelling mistakes, inaccurate spellings of brands, a few reworded sentences here and there that just make more sense, and periods when needed. Still in progress, I have to re-read all the pages over again to catch any that I missed the first few times around.

### CODE REVIEW

**Comment by uncenter** [comment]
I forgot to mention that I've been using [cSpell](https://cspell.org/) to help find these. I'll commit the settings file and package.json changes at some point later!

**Comment by uncenter** [comment]
I think at some point I or someone else might have to try to follow each hosting guide and see if they still work! I'm not very familiar or efficient with setting up databases and such so if anyone wants to go through the guides and see how they fare that would be great.

**Comment by uncenter** [comment]
Alright that's all the changes for this PR!

**Comment by mikecao** [comment]
Great work!

**Pull request merged**
